services:
    app:
      container_name: app
      build:
        dockerfile: Dockerfile
      command:
        - "python"
        - "run_main.py"
      restart: always
      ports:
        - "8000:8000"

    db:
      image: postgres:16.2
      container_name: db
      restart: always
      shm_size: 128mb
      env_file:
        - .env.docker
      volumes:
        - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
